name: CI

on:
  push:
    branches: [main]
  pull_request:

env:
  CI: true

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Lint
        run: bunx biome ci .

      - name: Typecheck
        run: bun run tsc --noEmit

      - name: Install Playwright browsers
        run: bunx playwright install --with-deps

      - name: Test
        run: bunx playwright test
